In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

In [2]:
n = 5 #no.of process

# arrival time from 0.0 to 5.0 
arrival_times = np.random.randint(0, 50, size = n) / 10

# burst time from 0 to 25
burst_times = np.random.randint(0, 26, size = n)

# priorities unique from 1 to 5
priorities = np.random.choice(range(1, 6), size = n, replace=False)
process_ids = ["Process " + str(i+1) for i in range(n)]
response_time = np.zeros(5)

In [3]:
#Creating a dataframe
data = {
    "Process ID": process_ids,
    "Arrival Time": arrival_times,
    "Burst Time": burst_times,
    "Priority": priorities,
    "Status": ["new"] * len(process_ids),
    "Response Time": response_time,
    "Waiting Time": response_time,
    "Turnaround Time": response_time
}

quest = pd.DataFrame(data)
quest.head(6)

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 1,1.1,6,3,new,0.0,0.0,0.0
1,Process 2,4.1,4,4,new,0.0,0.0,0.0
2,Process 3,3.0,0,2,new,0.0,0.0,0.0
3,Process 4,4.8,21,1,new,0.0,0.0,0.0
4,Process 5,0.6,24,5,new,0.0,0.0,0.0

In [4]:
#Final Report

def report(data):
    n = len(data)
    avg_resp = data['Response Time'].mean()
    avg_wait = data['Waiting Time'].mean()
    avg_turn = data['Turnaround Time'].mean()
 
    print(f"The average Response Time is: {avg_resp:.1f} unit time.")
    print(f"The average Waiting Time is: {avg_wait:.1f} unit time.")
    print(f"The average Turnaround Time is: {avg_turn:.1f} unit time.")

# First Come First Serve (FCFS) Scheduling

In [5]:
def fcfs_scheduling(data):
 
    n = len(data)
    data1 = data.sort_values(by='Arrival Time').reset_index(drop=True)
    t = 0

    for i in range(0,n):
        if t < data1['Arrival Time'][i]:
            t = data1['Arrival Time'][i]

        data1.at[i,"Response Time"] = t
        data1.at[i,"Waiting Time"] = t
        t = t + data1['Burst Time'][i]
        data1.at[i,"Turnaround Time"] = t
        data1.at[i,"Status"] = "Completed"

        display(data1.head())

    return data1

In [6]:
data1 = fcfs_scheduling(quest)

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,Completed,0.6,0.6,24.6
1,Process 1,1.1,6,3,new,0.0,0.0,0.0
2,Process 3,3.0,0,2,new,0.0,0.0,0.0
3,Process 2,4.1,4,4,new,0.0,0.0,0.0
4,Process 4,4.8,21,1,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,Completed,0.6,0.6,24.6
1,Process 1,1.1,6,3,Completed,24.6,24.6,30.6
2,Process 3,3.0,0,2,new,0.0,0.0,0.0
3,Process 2,4.1,4,4,new,0.0,0.0,0.0
4,Process 4,4.8,21,1,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,Completed,0.6,0.6,24.6
1,Process 1,1.1,6,3,Completed,24.6,24.6,30.6
2,Process 3,3.0,0,2,Completed,30.6,30.6,30.6
3,Process 2,4.1,4,4,new,0.0,0.0,0.0
4,Process 4,4.8,21,1,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,Completed,0.6,0.6,24.6
1,Process 1,1.1,6,3,Completed,24.6,24.6,30.6
2,Process 3,3.0,0,2,Completed,30.6,30.6,30.6
3,Process 2,4.1,4,4,Completed,30.6,30.6,34.6
4,Process 4,4.8,21,1,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,Completed,0.6,0.6,24.6
1,Process 1,1.1,6,3,Completed,24.6,24.6,30.6
2,Process 3,3.0,0,2,Completed,30.6,30.6,30.6
3,Process 2,4.1,4,4,Completed,30.6,30.6,34.6
4,Process 4,4.8,21,1,Completed,34.6,34.6,55.6

In [7]:
report(data1)

The average Response Time is: 24.2 unit time.
The average Waiting Time is: 24.2 unit time.
The average Turnaround Time is: 35.2 unit time.

# Shortest Job First Scheduling

In [8]:
def sjf_scheduling(data):
 
    n = len(data)
    data1 = data.sort_values(by='Arrival Time').reset_index(drop=True)
    t = 0
    completed_processes = 0
    process_queue = []
    current_time = data1['Arrival Time'][0]

    while completed_processes < n:

        # adding all processes that have arrived by the current time to the process queue
        for i in range(n):
            if data1.loc[i, 'Arrival Time'] <= current_time and data1.loc[i, 'Status'] == 'new':
                process_queue.append(i)
                data1.loc[i, 'Status'] = 'queued'

        # Select the process with the shortest burst time from the process queue
        if process_queue:
            next_process = min(process_queue, key=lambda x: data1.loc[x, 'Burst Time'])
            process_queue.remove(next_process)

            if t < data1.loc[next_process, 'Arrival Time']:
                t = data1.loc[next_process, 'Arrival Time']

            data1.loc[next_process, 'Response Time'] = t - data1.loc[next_process, 'Arrival Time']
            data1.loc[next_process, 'Waiting Time'] = t - data1.loc[next_process, 'Arrival Time']
            t += data1.loc[next_process, 'Burst Time']
            data1.loc[next_process, 'Turnaround Time'] = t - data1.loc[next_process, 'Arrival Time']
            data1.loc[next_process, 'Status'] = 'completed'
            completed_processes += 1
            current_time += data1.loc[next_process, 'Turnaround Time']

        display(data1.head(6))
    return data1

In [9]:
data1 = sjf_scheduling(quest)

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,completed,0.0,0.0,24.0
1,Process 1,1.1,6,3,new,0.0,0.0,0.0
2,Process 3,3.0,0,2,new,0.0,0.0,0.0
3,Process 2,4.1,4,4,new,0.0,0.0,0.0
4,Process 4,4.8,21,1,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,completed,0.0,0.0,24.0
1,Process 1,1.1,6,3,queued,0.0,0.0,0.0
2,Process 3,3.0,0,2,completed,21.6,21.6,21.6
3,Process 2,4.1,4,4,queued,0.0,0.0,0.0
4,Process 4,4.8,21,1,queued,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,completed,0.0,0.0,24.0
1,Process 1,1.1,6,3,queued,0.0,0.0,0.0
2,Process 3,3.0,0,2,completed,21.6,21.6,21.6
3,Process 2,4.1,4,4,completed,20.5,20.5,24.5
4,Process 4,4.8,21,1,queued,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,completed,0.0,0.0,24.0
1,Process 1,1.1,6,3,completed,27.5,27.5,33.5
2,Process 3,3.0,0,2,completed,21.6,21.6,21.6
3,Process 2,4.1,4,4,completed,20.5,20.5,24.5
4,Process 4,4.8,21,1,queued,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,completed,0.0,0.0,24.0
1,Process 1,1.1,6,3,completed,27.5,27.5,33.5
2,Process 3,3.0,0,2,completed,21.6,21.6,21.6
3,Process 2,4.1,4,4,completed,20.5,20.5,24.5
4,Process 4,4.8,21,1,completed,29.8,29.8,50.8

In [10]:
report(data1)

The average Response Time is: 19.9 unit time.
The average Waiting Time is: 19.9 unit time.
The average Turnaround Time is: 30.9 unit time.

# Priority Scheduling

In [11]:
def prior_scheduling(data):

    data1 = data.sort_values(by='Arrival Time').reset_index(drop=True)
    n = len(data)
    t = 0
    completed_processes = 0
    process_queue = []
    current_time = data1['Arrival Time'][0]

    while completed_processes < n:

        # Adding all processes that have arrived by the current time to the process queue
        for i in range(n):
            if data1.loc[i, 'Arrival Time'] <= current_time and data1.loc[i, 'Status'] == 'new':
                process_queue.append(i)
                data1.loc[i, 'Status'] = 'queued'

        # Select the process with the most priority (1 being max) from the process queue
        if process_queue:
            next_process = min(process_queue, key=lambda x: data1.loc[x, 'Priority'])
            process_queue.remove(next_process)

            if t < data1.loc[next_process, 'Arrival Time']:
                t = data1.loc[next_process, 'Arrival Time']

            data1.loc[next_process, 'Response Time'] = t - data1.loc[next_process, 'Arrival Time']
            data1.loc[next_process, 'Waiting Time'] = t - data1.loc[next_process, 'Arrival Time']
            t += data1.loc[next_process, 'Burst Time']
            data1.loc[next_process, 'Turnaround Time'] = t - data1.loc[next_process, 'Arrival Time']
            data1.loc[next_process, 'Status'] = 'completed'
            completed_processes += 1

        else:
            current_time += data1.loc[next_process, 'Turnaround Time']

        display(data1.head())
    return data1

In [12]:
data1 = prior_scheduling(quest)

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,completed,0.0,0.0,24.0
1,Process 1,1.1,6,3,new,0.0,0.0,0.0
2,Process 3,3.0,0,2,new,0.0,0.0,0.0
3,Process 2,4.1,4,4,new,0.0,0.0,0.0
4,Process 4,4.8,21,1,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,completed,0.0,0.0,24.0
1,Process 1,1.1,6,3,new,0.0,0.0,0.0
2,Process 3,3.0,0,2,new,0.0,0.0,0.0
3,Process 2,4.1,4,4,new,0.0,0.0,0.0
4,Process 4,4.8,21,1,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,completed,0.0,0.0,24.0
1,Process 1,1.1,6,3,queued,0.0,0.0,0.0
2,Process 3,3.0,0,2,queued,0.0,0.0,0.0
3,Process 2,4.1,4,4,queued,0.0,0.0,0.0
4,Process 4,4.8,21,1,completed,19.8,19.8,40.8

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,completed,0.0,0.0,24.0
1,Process 1,1.1,6,3,queued,0.0,0.0,0.0
2,Process 3,3.0,0,2,completed,42.6,42.6,42.6
3,Process 2,4.1,4,4,queued,0.0,0.0,0.0
4,Process 4,4.8,21,1,completed,19.8,19.8,40.8

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,completed,0.0,0.0,24.0
1,Process 1,1.1,6,3,completed,44.5,44.5,50.5
2,Process 3,3.0,0,2,completed,42.6,42.6,42.6
3,Process 2,4.1,4,4,queued,0.0,0.0,0.0
4,Process 4,4.8,21,1,completed,19.8,19.8,40.8

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 5,0.6,24,5,completed,0.0,0.0,24.0
1,Process 1,1.1,6,3,completed,44.5,44.5,50.5
2,Process 3,3.0,0,2,completed,42.6,42.6,42.6
3,Process 2,4.1,4,4,completed,47.5,47.5,51.5
4,Process 4,4.8,21,1,completed,19.8,19.8,40.8

In [13]:
report(data1)

The average Response Time is: 30.9 unit time.
The average Waiting Time is: 30.9 unit time.
The average Turnaround Time is: 41.9 unit time.

# Round Robin Scheduling

In [14]:
def rr_scheduling(data):

    n = len(data)
    #quantum at 70 percentile
    quantum = int(np.percentile(data['Burst Time'], 70))
    print(f"The quantum is of size : {quantum}.")
    data1 = data.sort_values(by='Arrival Time').reset_index(drop=True)
    data1['Remaining Burst Time'] = data1['Burst Time']

    current_time = data1['Arrival Time'][0]

    while not all(data1['Status'] == 'Completed'):

        for i in range(n):

            if data1.loc[i, 'Status'] == 'new':
                data1.at[i, 'Response Time'] = current_time - data1.loc[i, 'Arrival Time']
                data1.at[i, 'Status'] = 'Processing'

                if data1.loc[i, 'Remaining Burst Time'] > quantum:
                    current_time += quantum
                    data1.at[i, 'Remaining Burst Time'] -= quantum

                else: 
                    current_time += data1.loc[i, 'Remaining Burst Time']
                    data1.at[i, 'Remaining Burst Time'] = 0
                    data1.at[i, 'Turnaround Time'] = current_time - data1.loc[i, 'Arrival Time']
                    data1.at[i, 'Waiting Time'] = data1.loc[i, 'Turnaround Time'] - data1.loc[i, 'Burst Time'] 
                    data1.at[i, 'Status'] = 'Completed'

                display(data1.head(6))

        for i in range(n):

            if data1.loc[i, 'Status'] == 'Processing':

                if data1.loc[i, 'Remaining Burst Time'] > quantum:

                    current_time += quantum
                    data1.at[i, 'Remaining Burst Time'] -= quantum

                else:
                    current_time += data1.loc[i, 'Remaining Burst Time']
                    data1.at[i, 'Remaining Burst Time'] = 0
                    data1.at[i, 'Turnaround Time'] = current_time - data1.loc[i, 'Arrival Time']
                    data1.at[i, 'Waiting Time'] = data1.loc[i, 'Turnaround Time'] - data1.loc[i, 'Burst Time'] 
                    data1.at[i, 'Status'] = 'Completed'

                display(data1.head(6))

    return data1

In [15]:
data1 = rr_scheduling(quest)

The quantum is of size : 17.

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 5,0.6,24,5,Processing,0.0,0.0,0.0,7
1,Process 1,1.1,6,3,new,0.0,0.0,0.0,6
2,Process 3,3.0,0,2,new,0.0,0.0,0.0,0
3,Process 2,4.1,4,4,new,0.0,0.0,0.0,4
4,Process 4,4.8,21,1,new,0.0,0.0,0.0,21

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 5,0.6,24,5,Processing,0.0,0.0,0.0,7
1,Process 1,1.1,6,3,Completed,16.5,16.5,22.5,0
2,Process 3,3.0,0,2,new,0.0,0.0,0.0,0
3,Process 2,4.1,4,4,new,0.0,0.0,0.0,4
4,Process 4,4.8,21,1,new,0.0,0.0,0.0,21

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 5,0.6,24,5,Processing,0.0,0.0,0.0,7
1,Process 1,1.1,6,3,Completed,16.5,16.5,22.5,0
2,Process 3,3.0,0,2,Completed,20.6,20.6,20.6,0
3,Process 2,4.1,4,4,new,0.0,0.0,0.0,4
4,Process 4,4.8,21,1,new,0.0,0.0,0.0,21

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 5,0.6,24,5,Processing,0.0,0.0,0.0,7
1,Process 1,1.1,6,3,Completed,16.5,16.5,22.5,0
2,Process 3,3.0,0,2,Completed,20.6,20.6,20.6,0
3,Process 2,4.1,4,4,Completed,19.5,19.5,23.5,0
4,Process 4,4.8,21,1,new,0.0,0.0,0.0,21

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 5,0.6,24,5,Processing,0.0,0.0,0.0,7
1,Process 1,1.1,6,3,Completed,16.5,16.5,22.5,0
2,Process 3,3.0,0,2,Completed,20.6,20.6,20.6,0
3,Process 2,4.1,4,4,Completed,19.5,19.5,23.5,0
4,Process 4,4.8,21,1,Processing,22.8,0.0,0.0,4

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 5,0.6,24,5,Completed,0.0,27.0,51.0,0
1,Process 1,1.1,6,3,Completed,16.5,16.5,22.5,0
2,Process 3,3.0,0,2,Completed,20.6,20.6,20.6,0
3,Process 2,4.1,4,4,Completed,19.5,19.5,23.5,0
4,Process 4,4.8,21,1,Processing,22.8,0.0,0.0,4

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 5,0.6,24,5,Completed,0.0,27.0,51.0,0
1,Process 1,1.1,6,3,Completed,16.5,16.5,22.5,0
2,Process 3,3.0,0,2,Completed,20.6,20.6,20.6,0
3,Process 2,4.1,4,4,Completed,19.5,19.5,23.5,0
4,Process 4,4.8,21,1,Completed,22.8,29.8,50.8,0

In [16]:
report(data1)

The average Response Time is: 15.9 unit time.
The average Waiting Time is: 22.7 unit time.
The average Turnaround Time is: 33.7 unit time.

Conclusion

Through simulation, we observed the trade-offs involved in each scheduling algorithm. FCFS is straightforward but can be inefficient. SJF optimizes waiting time but is difficult to implement practically. Priority Scheduling is flexible but risks starvation without safeguards. Round Robin offers balanced performance but requires careful tuning of its parameters. Understanding these algorithms helps in designing better CPU scheduling mechanisms to optimize performance metrics such as turnaround time, waiting time, and response time in operating systems.